-- Run this in the Supabase SQL editor AFTER you have run the webapp and logged in at least once. You need to make sure the `profiles` table has at least one user in it.
-- This will populate the database with some seed data you can use, with the author for each species set to the first user in the `profiles` table.

-- commentid int unique generated by default as identity primary key,
  scientific_name text not null references species(scientific_name),
  speciesid int,
  common_name_sugs text,
  total_population_sugs int,
  kingdom_sugs kingdom,
  description_sugs text,
  image_sugs text,
  other_sugs text,
  time_made timestamp,
  author uuid not null references profiles



do $$
declare
  user_id uuid;
begin
  select id from profiles limit 1 into user_id;

  insert into
  comments(scientific_name_sugs,	common_name_sugs,	total_population_sugs,	kingdom_sugs,	description_sugs,	author,	image_sugs, other_sugs)
  values
    (null,	null,	null,	null,	null, user_id,	null, null),
    (null,	null,	null,	null,	null, user_id,	null, null),
    (null,	null,	null,	null,	null, user_id,	null, null),
    (null,	null,	null,	null,	null, user_id,	null, null),
    (null,	null,	null,	null,	null, user_id,	null, null),
    (null,	null,	null,	null,	null, user_id,	null, null),
    (null,	null,	null,	null,	null, user_id,	null, null),
    (null,	null,	null,	null,	null, user_id,	null, null),
    (null,	null,	null,	null,	null, user_id,	null, null),
    (null,	null,	null,	null,	null, user_id,	null, null),
    (null,	null,	null,	null,	null, user_id,	null, null),
    (null,	null,	null,	null,	null, user_id,	null, null),
    (null,	null,	null,	null,	null, user_id,	null, null),
    (null,	null,	null,	null,	null, user_id,	null, null),
    (null,	null,	null,	null,	null, user_id,	null, null),
    (null,	null,	null,	null,	null, user_id,	null, null);

end; $$;
